-- Migration: Add cancellation, rescheduling, and pre-screening notification types

USE blood_donation_db;

ALTER TABLE notifications
MODIFY COLUMN type ENUM(
  'BLOOD_REQUEST',
  'SHARE_REQUEST',
  'REQUEST_ACCEPTED',
  'CAMPAIGN',
  'DONATION_COMPLETED',
  'EVENT_REMINDER_24H',
  'EVENT_REMINDER_2H',
  'EVENT_WAITLIST_SPOT_AVAILABLE',
  'EVENT_CHECKIN_CONFIRMED',
  'EVENT_CANCELLED',
  'EVENT_RESCHEDULED',
  'PRE_SCREENING_REMINDER',
  'PRE_SCREENING_COMPLETED',
  'PRE_SCREENING_INELIGIBLE'
) NOT NULL;
